import json
import logging
import os
from pathlib import Path

from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

from state import PaperState
from config import output_config

logger = logging.getLogger(__name__)


def export_to_docx(state: PaperState, filename: str = "paper.docx") -> str:
    """导出论文为Word文档"""
    topic = state.get("topic", "Untitled")
    sections = state.get("sections", {})
    reviews = state.get("reviews", {})
    outline_data = json.loads(state.get("outline", "{}"))
    chapters = outline_data.get("chapters", [])

    os.makedirs(output_config.output_dir, exist_ok=True)
    filepath = os.path.join(output_config.output_dir, filename)

    doc = Document()

    title = doc.add_heading(topic, 0)
    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    doc.add_paragraph(f"Generated by Multi-Agent Paper Writer System")

    for chapter in chapters:
        chapter_title = chapter.get("chapter", "")
        content = sections.get(chapter_title, "")

        doc.add_heading(chapter_title, level=1)

        if content:
            for para in content.split("\n"):
                para = para.strip()
                if para:
                    if para.startswith("# "):
                        doc.add_heading(para[2:], level=2)
                    elif para.startswith("## "):
                        doc.add_heading(para[3:], level=3)
                    else:
                        doc.add_paragraph(para)
        else:
            doc.add_paragraph("[Content not available]")

        review = reviews.get(chapter_title)
        if review:
            doc.add_paragraph()
            review_para = doc.add_paragraph()
            review_para.add_run("Review Score: ").bold = True
            review_para.add_run(f"{review.score:.2f}/1.00")
            doc.add_paragraph(f"Decision: {review.decision.value}")
            doc.add_paragraph(f"Feedback: {review.feedback}")

    doc.save(filepath)
    logger.info(f"Document saved to: {filepath}")
    return filepath


def export_to_markdown(state: PaperState, filename: str = "paper.md") -> str:
    """导出论文为Markdown格式"""
    topic = state.get("topic", "Untitled")
    sections = state.get("sections", {})
    reviews = state.get("reviews", {})
    outline_data = json.loads(state.get("outline", "{}"))
    chapters = outline_data.get("chapters", [])

    os.makedirs(output_config.output_dir, exist_ok=True)
    filepath = os.path.join(output_config.output_dir, filename)

    lines = [f"# {topic}\n", f"*{topic}*\n"]

    for chapter in chapters:
        chapter_title = chapter.get("chapter", "")
        content = sections.get(chapter_title, "")
        review = reviews.get(chapter_title)

        lines.append(f"\n## {chapter_title}\n")

        if content:
            lines.append(content)
        else:
            lines.append("*Content not available*")

        if review:
            lines.append(f"\n**Review Score:** {review.score:.2f}/1.00")
            lines.append(f"**Decision:** {review.decision.value}")
            lines.append(f"**Feedback:** {review.feedback}\n")

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    logger.info(f"Markdown saved to: {filepath}")
    return filepath


def export_paper(state: PaperState, filename: str = None) -> str:
    """根据配置导出论文"""
    topic = state.get("topic", "paper").replace(" ", "_")
    fmt = output_config.format

    if filename is None:
        filename = f"{topic}.{fmt}"

    if fmt == "docx":
        return export_to_docx(state, filename)
    elif fmt == "md" or fmt == "markdown":
        return export_to_markdown(state, filename)
    else:
        raise ValueError(f"Unsupported format: {fmt}")